In [2]:
print("Hello World")

Hello World

In [4]:
import pandas as pd

df = pd.read_csv(r'/kaggle/input/datasets/alwinchetty/ner-csv/ner.csv')

In [5]:
df.head(10)

,Sentence #,Sentence,POS,Tag
0,Sentence: 1,Thousands of demonstrators have marched throug...,"['NNS', 'IN', 'NNS', 'VBP', 'VBN', 'IN', 'NNP'...","['O', 'O', 'O', 'O', 'O', 'O', 'B-geo', 'O', '..."
1,Sentence: 2,Families of soldiers killed in the conflict jo...,"['NNS', 'IN', 'NNS', 'VBN', 'IN', 'DT', 'NN', ...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
2,Sentence: 3,They marched from the Houses of Parliament to ...,"['PRP', 'VBD', 'IN', 'DT', 'NNS', 'IN', 'NN', ...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
3,Sentence: 4,"Police put the number of marchers at 10,000 wh...","['NNS', 'VBD', 'DT', 'NN', 'IN', 'NNS', 'IN', ...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
4,Sentence: 5,The protest comes on the eve of the annual con...,"['DT', 'NN', 'VBZ', 'IN', 'DT', 'NN', 'IN', 'D...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
5,Sentence: 6,The party is divided over Britain 's participa...,"['DT', 'NN', 'VBZ', 'VBN', 'IN', 'NNP', 'POS',...","['O', 'O', 'O', 'O', 'O', 'B-gpe', 'O', 'O', '..."
6,Sentence: 7,The London march came ahead of anti-war protes...,"['DT', 'NNP', 'NN', 'VBD', 'RB', 'IN', 'JJ', '...","['O', 'B-geo', 'O', 'O', 'O', 'O', 'O', 'O', '..."
7,Sentence: 8,The International Atomic Energy Agency is to h...,"['DT', 'NNP', 'NNP', 'NNP', 'NNP', 'VBZ', 'TO'...","['O', 'B-org', 'I-org', 'I-org', 'I-org', 'O',..."
8,Sentence: 9,Iran this week restarted parts of the conversi...,"['NNP', 'DT', 'NN', 'VBD', 'NNS', 'IN', 'DT', ...","['B-gpe', 'O', 'O', 'O', 'O', 'O', 'O', 'O', '..."
9,Sentence: 10,Iranian officials say they expect to get acces...,"['JJ', 'NNS', 'VBP', 'PRP', 'VBP', 'TO', 'VB',...","['B-gpe', 'O', 'O', 'O', 'O', 'O', 'O', 'O', '..."

In [6]:
type(df['Tag'][0])

str

In [7]:
type(df['POS'][0])

str

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47959 entries, 0 to 47958
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Sentence #  47959 non-null  object
 1   Sentence    47959 non-null  object
 2   POS         47959 non-null  object
 3   Tag         47959 non-null  object
dtypes: object(4)
memory usage: 1.5+ MB

In [9]:
df.describe()

,Sentence #,Sentence,POS,Tag
count,47959,47959,47959,47959
unique,47959,47575,47214,33318
top,Sentence: 1,VOA 's Mil Arcega reports .,"['NNP', 'POS', 'NNP', 'NNP', 'VBZ', '.']","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
freq,1,17,39,450

In [10]:
# converting the str to list using literal_eval

from ast import literal_eval

df['POS'] = df['POS'].apply(literal_eval)

df['Tag'] = df['Tag'].apply(literal_eval)

In [11]:
type(df['POS'][0])

list

In [12]:
type(df['Tag'][0])

list

In [13]:
unique_tags = df['Tag'].explode().unique()

In [14]:
unique_tags[1:11]

array(['B-geo', 'B-gpe', 'B-per', 'I-geo', 'B-org', 'I-org', 'B-tim',
       'B-art', 'I-art', 'I-per'], dtype=object)

In [15]:
sorted_tags = sorted(unique_tags)

In [16]:
sorted_tags[:11]

['B-art',
 'B-eve',
 'B-geo',
 'B-gpe',
 'B-nat',
 'B-org',
 'B-per',
 'B-tim',
 'I-art',
 'I-eve',
 'I-geo']

In [17]:
label2id = {label: id for id, label in enumerate(sorted_tags)}
id2label = {id: label for id, label in enumerate(sorted_tags)}

In [18]:
label2id

{'B-art': 0,
 'B-eve': 1,
 'B-geo': 2,
 'B-gpe': 3,
 'B-nat': 4,
 'B-org': 5,
 'B-per': 6,
 'B-tim': 7,
 'I-art': 8,
 'I-eve': 9,
 'I-geo': 10,
 'I-gpe': 11,
 'I-nat': 12,
 'I-org': 13,
 'I-per': 14,
 'I-tim': 15,
 'O': 16}

In [19]:
id2label

{0: 'B-art',
 1: 'B-eve',
 2: 'B-geo',
 3: 'B-gpe',
 4: 'B-nat',
 5: 'B-org',
 6: 'B-per',
 7: 'B-tim',
 8: 'I-art',
 9: 'I-eve',
 10: 'I-geo',
 11: 'I-gpe',
 12: 'I-nat',
 13: 'I-org',
 14: 'I-per',
 15: 'I-tim',
 16: 'O'}

In [20]:
print(len(sorted_tags))

17

In [21]:
print(len(label2id))
print(len(id2label))

17
17

In [22]:
from transformers.models.auto import AutoTokenizer

In [23]:
MODEL_NAME = 'microsoft/deberta-v3-small'

In [24]:
tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/578 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

In [25]:
sentence_tokenize = tokenizer.tokenize(df['Sentence'][0])

In [26]:
sentence_tokenize

['▁Thousands',
 '▁of',
 '▁demonstrators',
 '▁have',
 '▁marched',
 '▁through',
 '▁London',
 '▁to',
 '▁protest',
 '▁the',
 '▁war',
 '▁in',
 '▁Iraq',
 '▁and',
 '▁demand',
 '▁the',
 '▁withdrawal',
 '▁of',
 '▁British',
 '▁troops',
 '▁from',
 '▁that',
 '▁country',
 '▁.']

In [27]:
if len(sentence_tokenize) == len(df['Tag'][0]):
    print("The length is same")
else:
    print("The length is not same")

The length is same

In [28]:
len(sentence_tokenize)

24

In [29]:
len(df['Tag'][0])

24

In [30]:
sentence = "Good Morning India"

word = sentence.split()

In [31]:
word

['Good', 'Morning', 'India']

In [32]:
df['Words'] = df['Sentence'].apply(lambda x: x.split())

In [33]:
df['Words'].head(10)

0    [Thousands, of, demonstrators, have, marched, ...
1    [Families, of, soldiers, killed, in, the, conf...
2    [They, marched, from, the, Houses, of, Parliam...
3    [Police, put, the, number, of, marchers, at, 1...
4    [The, protest, comes, on, the, eve, of, the, a...
5    [The, party, is, divided, over, Britain, 's, p...
6    [The, London, march, came, ahead, of, anti-war...
7    [The, International, Atomic, Energy, Agency, i...
8    [Iran, this, week, restarted, parts, of, the, ...
9    [Iranian, officials, say, they, expect, to, ge...
Name: Words, dtype: object

In [34]:
type(df['Words'][0])

list

In [35]:
df['Words'].apply(len) == df['Tag'].apply(len)

0        True
1        True
2        True
3        True
4        True
         ...
47954    True
47955    True
47956    True
47957    True
47958    True
Length: 47959, dtype: bool

### In PyTorch (the library powering the model), -100 is a special "ignore index" number.

In [36]:
def align_labels_with_tokens(labels, word_ids):

    new_labels = []
    previous_word_idx = None

    for word_idx in word_ids:
        if word_idx is None:
            new_labels.append(-100)
        elif word_idx != previous_word_idx:
            found_label_id = label2id[labels[word_idx]]
            new_labels.append(found_label_id)
        else:
            new_labels.append((-100))
            
        previous_word_idx = word_idx

    return new_labels

In [38]:
test_inputs = tokenizer(df['Words'][100], is_split_into_words=True)

In [40]:
test_word_ids = test_inputs.word_ids()

In [41]:
test_word_ids

[0, 1, 2, 3, 4, 5, 6, 7, 7, 7, 8, 9, 10, 11, 12]

In [42]:
test_labels = df['Tag'][100]

In [43]:
test_labels

['O', 'B-gpe', 'O', 'O', 'O', 'O', 'O', 'B-geo', 'O', 'O', 'B-org', 'O', 'O']

In [44]:
align_labels_with_tokens(test_labels, test_word_ids)

[16, 3, 16, 16, 16, 16, 16, 2, -100, -100, 16, 16, 5, 16, 16]

In [45]:
df['Words'][100]

['The',
 'Pakistani',
 'military',
 'launched',
 'its',
 'offensive',
 'in',
 'Orakzai',
 'to',
 'hunt',
 'Taliban',
 'insurgents',
 '.']

In [46]:
df['Tag'][100]

['O', 'B-gpe', 'O', 'O', 'O', 'O', 'O', 'B-geo', 'O', 'O', 'B-org', 'O', 'O']

In [47]:
type(df)

pandas.core.frame.DataFrame

In [56]:
from datasets import Dataset

raw_dataset = Dataset.from_pandas(df)

In [49]:
def tokenize_and_align_labels(examples):

    tokenized_inputs = tokenizer(examples['Words'], truncation=True, is_split_into_words=True)

    labels_list = []

    for i, labels in enumerate(examples['Tag']):
        word_ids = tokenized_inputs.word_ids(batch_index=i)

        aligned_labels = align_labels_with_tokens(labels, word_ids)
        labels_list.append(aligned_labels)
    
    tokenized_inputs['labels'] = labels_list

    return tokenized_inputs

In [50]:
type(raw_dataset)

datasets.arrow_dataset.Dataset

In [57]:
raw_dataset

Dataset({
    features: ['Sentence #', 'Sentence', 'POS', 'Tag', 'Words'],
    num_rows: 47955
})

tokenize_and_align_labels(raw_dataset) -? this could process all num of rows at a single time and could crash the RAM

In [55]:
df = df[df['Words'].apply(len) == df['Tag'].apply(len)].reset_index(drop=True)

In [58]:
tokenized_dataset = raw_dataset.map(tokenize_and_align_labels, batched=True, batch_size=1000)

Map:   0%|          | 0/47955 [00:00<?, ? examples/s]

In [59]:
tokenized_dataset[4071]

{'Sentence #': 'Sentence: 4073',
 'Sentence': 'Grieving families in northern Iraq have canceled plans for a mass funeral for dozens of suicide bomb victims because of concerns it would be attacked .',
 'POS': ['VBG',
  'NNS',
  'IN',
  'JJ',
  'NNP',
  'VBP',
  'VBN',
  'NNS',
  'IN',
  'DT',
  'NN',
  'NN',
  'IN',
  'NNS',
  'IN',
  'NN',
  'NN',
  'NNS',
  'IN',
  'IN',
  'NNS',
  'PRP',
  'MD',
  'VB',
  'VBN',
  '.'],
 'Tag': ['O',
  'O',
  'O',
  'O',
  'B-geo',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O'],
 'Words': ['Grieving',
  'families',
  'in',
  'northern',
  'Iraq',
  'have',
  'canceled',
  'plans',
  'for',
  'a',
  'mass',
  'funeral',
  'for',
  'dozens',
  'of',
  'suicide',
  'bomb',
  'victims',
  'because',
  'of',
  'concerns',
  'it',
  'would',
  'be',
  'attacked',
  '.'],
 'input_ids': [121808,
  1549,
  267,
  4570,
  4516,
  286,
  14588,
  1254,
  270,
  266,
  2675,
  6825,
  270,
  6361,
  265,
  5997,
  7495,
  3760,
  401,
  265,
  2372,
  278,
  338,
  282,
  6674,
  323],
 'token_type_ids': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'labels': [16,
  16,
  16,
  16,
  2,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16,
  16]}

In [60]:
train_test_split = tokenized_dataset.train_test_split(
    0.1, seed = 42
)

In [61]:
from transformers import AutoModelForTokenClassification

In [62]:
MODEL_NAME = "microsoft/deberta-v3-small"

In [63]:
model = AutoModelForTokenClassification.from_pretrained(
    MODEL_NAME,
    num_labels = 17,
    label2id = label2id,
    id2label = id2label
)

pytorch_model.bin:   0%|          | 0.00/286M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/102 [00:00<?, ?it/s]

DebertaV2ForTokenClassification LOAD REPORT from: microsoft/deberta-v3-small
Key                                     | Status     |
----------------------------------------+------------+-
lm_predictions.lm_head.dense.weight     | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.weight | UNEXPECTED |
lm_predictions.lm_head.bias             | UNEXPECTED |
mask_predictions.classifier.weight      | UNEXPECTED |
mask_predictions.LayerNorm.weight       | UNEXPECTED |
mask_predictions.dense.bias             | UNEXPECTED |
mask_predictions.LayerNorm.bias         | UNEXPECTED |
mask_predictions.classifier.bias        | UNEXPECTED |
lm_predictions.lm_head.dense.bias       | UNEXPECTED |
lm_predictions.lm_head.LayerNorm.bias   | UNEXPECTED |
mask_predictions.dense.weight           | UNEXPECTED |
classifier.bias                         | MISSING    |
classifier.weight                       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

model.safetensors:   0%|          | 0.00/286M [00:00<?, ?B/s]

In [64]:
from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

In [65]:
import numpy as np
from sklearn.metrics import f1_score

def compute_metrics(eval_preds):
    logits, labels = eval_preds
    predictions = np.argmax(logits, axis=-1)
    
    # Filter out -100 (ignored tokens)
    true_labels = []
    true_predictions = []
    
    for prediction, label in zip(predictions, labels):
        for p, l in zip(prediction, label):
            if l != -100:
                true_labels.append(l)
                true_predictions.append(p)
                
    return {
        "f1": f1_score(true_labels, true_predictions, average="macro")
    }

In [66]:
from peft import LoraConfig, get_peft_model, TaskType

In [67]:
lora_config = LoraConfig(
    task_type=TaskType.TOKEN_CLS,    
    inference_mode=False,
    r=16,                             
    lora_alpha=32,                    
    lora_dropout=0.1,
    target_modules=["query_proj", "value_proj"]  
)

In [68]:
model = get_peft_model(
    model,
    lora_config
)

In [69]:
model.print_trainable_parameters()

trainable params: 307,985 || all params: 141,625,378 || trainable%: 0.2175

In [70]:
from transformers import TrainingArguments

In [75]:
training_args = TrainingArguments(
    output_dir = './results',
    learning_rate = 1e-4,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 16,
    num_train_epochs = 6,
    weight_decay = 0.01,
    eval_strategy = 'epoch',
    save_strategy = 'epoch',
    load_best_model_at_end = True,
    metric_for_best_model = 'f1',
    # fp16 = True, kaggle gpu doesnt support this or fp32
    logging_steps = 100,
    warmup_steps = 1100,
    lr_scheduler_type = 'linear'
)

In [76]:
from transformers import Trainer

In [78]:
trainer = Trainer(
    model = model,
    args = training_args,
    train_dataset = train_test_split['train'],
    eval_dataset = train_test_split['test'],
    processing_class = tokenizer,
    data_collator = data_collator,
    compute_metrics = compute_metrics
)

In [79]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]
/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py:583: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  return super().apply(*args, **kwargs)  # type: ignore[misc]

TrainOutput(global_step=8094, training_loss=0.8075494712035922, metrics={'train_runtime': 1127.0681, 'train_samples_per_second': 229.759, 'train_steps_per_second': 7.181, 'total_flos': 2959268008924524.0, 'train_loss': 0.8075494712035922, 'epoch': 6.0})

In [ ]:
# Save the LoRA adapters
model.save_pretrained("./deberta_lora_adapters")

# Save the tokenizer so they stay together
tokenizer.save_pretrained("./deberta_lora_adapters")